/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "actionText": "Get Started →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "Simplicity First",
            "details": "Minimal setup with markdown-centered project structure helps you focus on writing."
          },
          {
            "title": "Vue-Powered",
            "details": "Enjoy the dev experience of Vue + webpack, use Vue components in markdown, and develop custom themes with Vue."
          },
          {
            "title": "Performant",
            "details": "VuePress generates pre-rendered static HTML for each page, and runs as an SPA once a page is loaded."
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-2ac27455",
      "path": "/"
    },
    {
      "frontmatter": {},
      "regularPath": "/install_vuepress.html",
      "relativePath": "install_vuepress.md",
      "key": "v-e47e8760",
      "path": "/install_vuepress.html"
    }
  ],
  "themeConfig": {}
}